# Generated by Django 5.2.14 on 2026-09-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('frequency_days', models.IntegerField(help_text='e.g. 1 = daily, 7 = weekly')),
                ('rotation_order', models.JSONField(help_text='List of Person IDs, in turn order')),
                ('rotation_index', models.IntegerField(default=0, help_text='Index into rotation_order for whose turn it is')),
                ('due_date', models.DateField()),
                ('grace_hours', models.IntegerField(default=24, help_text='Hours after due_date before escalating')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reminded', 'Reminded'), ('escalated', 'Escalated'), ('done', 'Done')], default='pending', max_length=20)),
            ],
        ),
    ]
