# Generated by Django 5.2.14 on 2026-09-16 00:13

import chores.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionToken',
            fields=[
                ('token', models.CharField(default=chores.models.generate_token, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_tokens', to='chores.chore')),
            ],
        ),
    ]
